server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: root
  Jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  api-docs:
    path: /api/open-api
  swagger-ui:
    path: /api/open-api.html